HEADER
build.gradle
src/main/java/io/pravega/connectors/flink/CheckpointSerializer.java
src/main/java/io/pravega/connectors/flink/FlinkExactlyOncePravegaWriter.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/main/java/io/pravega/connectors/flink/PravegaEventRouter.java
src/main/java/io/pravega/connectors/flink/PravegaWriterMode.java
src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java
src/test/java/io/pravega/connectors/flink/FlinkExactlyOncePravegaWriterTest.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderSavepointTest.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java
src/test/java/io/pravega/connectors/flink/ThrottledIntegerGeneratingSource.java
src/test/java/io/pravega/connectors/flink/utils/FailingMapper.java
src/test/java/io/pravega/connectors/flink/utils/FlinkMiniClusterWithSavepointCommand.java
src/test/java/io/pravega/connectors/flink/utils/IntSequenceExactlyOnceValidator.java
src/test/java/io/pravega/connectors/flink/utils/IntegerGeneratingSource.java
src/test/java/io/pravega/connectors/flink/utils/IntegerSerializer.java
src/test/java/io/pravega/connectors/flink/utils/IntentionalException.java
src/test/java/io/pravega/connectors/flink/utils/NotifyingMapper.java
src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java
src/test/java/io/pravega/connectors/flink/utils/SuccessException.java
src/test/java/io/pravega/connectors/flink/utils/TestUtils.java
src/test/java/io/pravega/connectors/flink/utils/ThrottledIntegerWriter.java

Now that we have finalized to license under Apache 2.0, here are the changes that are requested before we open source the repo.

License header fix for ALv2

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java

Addressed classloader issue when master invokes reader checkpoint hook.  Closes #24 
Reader Group makes use of grpc package which uses thread context classloader that causes some of its dependencies not getting loaded properly when the master hook is invoked.
Uses appropriate classloader while invoking Reader group class in `ReaderCheckpointHook
Running a sample code that uses `FlinkPravegaReader` to read from Pravega stream on a Flink cluster will throw below exception without this fix.
```
io.pravega.shaded.io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact
```

Issue 24 - ReaderCheckpointHook failure

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java

Closes #19
Replaced default reader name from using UUID to a stable reader name using stream and scope names
Since `readerName` is used as checkpoint identifier, a random UUID default value will cause the job to fail when recovering from savepoint
It derives a stable reader name using stream/scope name combination when reader name is not supplied
Run a Flink job which uses FlinkPragevaReader as a source (do not pass readerName to the pravega reader class). While the job is running, create a savepoint and try to restart the job from the savepoint. The job will fail to run since the reader name does not match with the previous run. With this fix, the job can be recovered with savepoint.

[Issue 19] Use a stable default readerName 

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java

Minor change to provide a meaningful name to `readerId`.  Closes #16.
To improve the log readability.
It uses a combination of task name + subtask indicator to derive the reader name.
The task manager log should dump the reader id information with the above mentioned format when the reader is created.

[Issue 16] modified reader id to use a meaningful name for log readability

---

README.md

This pull request fixes #36 
**NOTE:** This assumes that #37 is merged, because it references the `1.3.1` version dependency.
Updates the `README.md` with 
- A slightly richer introduction
- List of connector highlights
- A reference to the Flink release this depends on
- Java code syntax highlighting in the examples section

[Issue 36] Improve README.md

---

gradle.properties

Pull request for #35 
Bumps the linked Flink version from `1.3-SNAPSHOT` to `1.3.1`.
**Verification**
Tests (`./gradlew test`) passes for the `1.3.1` dependency.

[ISSUE-35] Change Flink version to stable 1.3.1 release

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/serialization/PravegaDeserializationSchema.java
src/main/java/io/pravega/connectors/flink/serialization/PravegaSerializationSchema.java
src/main/java/io/pravega/connectors/flink/serialization/WrappingSerializer.java
src/test/java/io/pravega/connectors/flink/FlinkSerializerWrapperTest.java
src/test/java/io/pravega/connectors/flink/serialization/PravegaSerializationTest.java

Adds various small improvements to the `PravegaDeserializationSchema`:
- Avoid redundant double-wrapping of serializers in FlinkPraveaReader
- Adds a check that the Pavega serializer is serializable (otherwise this gives an exception on execution).
- Fully support Flink's type information spectrum (also generic types that need to be captured)
- Add more convenience constructors
Checkstyle and unit tests pass.

Usability improvements for PravegaDeserializationSchema

---

build.gradle
gradle.properties
src/main/java/io/pravega/connectors/flink/EventTimeOrderingOperator.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/main/java/io/pravega/connectors/flink/util/FlinkPravegaUtils.java
src/main/java/io/pravega/connectors/flink/util/PravegaEventRouterKeySelector.java
src/test/java/io/pravega/connectors/flink/EventTimeOrderingOperatorTest.java

Support for event time ordering of elements produced by the sink.
Closes issue #45.
This PR provides a facility for reordering a program's output events into event time order, in combination with the natural ordering guarantee of Pravega routing keys.   It works by combining a keyed stream, a custom operator that reorders elements, and a forwarding strategy to the normal sink.
The code provides three new classes:
- `EventTimeOrderingOperator` - a generic operator that reorders events into event time (using the watermark to flush event buffers).
- `PravegaEventRouterKeySelector` - a helper class to use a pravega event router as the key selector for a Flink keyed stream.
- `FlinkPravegaUtils` - a convenience method …

Support for event time ordering of elements produced by the sink

---

src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java

Sets a port for the rest server.
This will fix errors when `InProcPravegaCluster` is instantiated during the tests.
Sets a value for the port.
Unit tests do not fail at  `InProcPravegaCluster` initialization.

Setting a port for restserver.

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java

Simple fix of an invalid argument sanity check, where the incorrect variable was verified in `FlinkPravegaReader.setEventReadTimeout`.

[misc] Fix invalid argument sanity check on FlinkPravegaReader#setEventReadTimeout

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaInputFormat.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/util/FlinkPravegaUtils.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaInputFormatTest.java
src/test/java/io/pravega/connectors/flink/FlinkSerializerWrapperTest.java
src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java

- 2fe0e92 preliminary fix for #53 
- 12a2fe3 introduce `FlinkPravegaInputFormat`
Add batch support to the connector. Users can add the `FlinkPravegaInputFormat` as a source to Flink batch jobs.
**Known pitfalls / limitations**
- Reader group creation is performed on the client. Apparently, Flink's `InitializeOnMaster` and `FinalizeOnMaster` hooks only currently works for `OutputFormat`s, so we can't use them for the one-time reader group creation / deletion.
- The "end of input" marker is quite brittle at the moment. The PR simply uses a return of `null` on of the last read event `EventRead.getEvent()` as an indicator. We might want to add some retry logic there to strengthen that, and avoid cases where the `null` return was just caused …

[Issue #42] Add initial batch read support for Flink Pravega Connectors

---

src/main/java/io/pravega/connectors/flink/util/FlinkPravegaUtils.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java

…for event time-ordered sink.
Closes #58.
- Make explicit the 'forwarding' partitioning strategy.  Was implicit before.
- Code cleanup to better express the intent.
Added a manual test `FlinkPravegaWriterTest::testEventTimeOrderedWriter`.  Observe the execution plan to note that a forward strategy is used.

[issue-58] Make explicit the 'forwarding' partitioning strategy

---

build.gradle
checkstyle/import-control.xml
gradle.properties
src/main/java/io/pravega/connectors/flink/FlinkPravegaTableSink.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaTableSource.java
src/main/java/io/pravega/connectors/flink/serialization/JsonRowDeserializationSchema.java
src/main/java/io/pravega/connectors/flink/serialization/JsonRowSerializationSchema.java
src/test/java/io/pravega/connectors/flink/FlinkTableITCase.java

- add `FlinkPravegaTableSource`
- add `FlinkPravegaTableSink`
- add `FlinkTableITCase`
- add JSON serialization schema
- add jackson as a 'provided' (by Flink) dependency
Introduces Flink Table API support, including a table source and append-only table sink.  Closes #32 .
Execute integration test `FlinkTableITCase`.

[issue-32] Table Connector

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java

- remove obsolete code
Removes workaround code related to checkpoint hooks during development of Flink 1.3.  
Closes #28.
- test that a job w/ checkpoints enabled is runnable on a Flink 1.3+ cluster.

[issue-28] Remove workaround code

---

build.gradle
gradle.properties
src/main/java/io/pravega/connectors/flink/util/FlinkPravegaUtils.java

I think we accidentally used lang(2)'s RandomStringUtils. This was being silently fetched into the uber jar because Pravega had it as a dependency. They've dropped it in on master.
This class is deprecated. Talking it over with Eron, we feel using a deprecated class is better than bringing the entire commons-text package.

Use lang3.RandomStringUtils

---

build.gradle

Similar to #80. A dependency is using a class from netty or netty-all that we're not including in the uber jar. This is causing a ClassDefNotFound. (Note: in shadowjars we need to include transitive dependencies explicitly. Both netty and netty-all are transitive dependencies.)

Add netty and netty-all to dependency list

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java

- `FlinkPravegaReader` acquire checkpoint lock as required by `SourceFunction`
- Avoid a potential concurrency issue.  Closes #63.
- Run existing integration test `FlinkPravegaReaderTest`

[issue-63] FlinkPravegaReader must synchronize on checkpoint lock

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaInputFormat.java
src/main/java/io/pravega/connectors/flink/PravegaInputSplit.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaInputFormatITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaInputFormatTest.java

- Reworks the `FlinkPravegaInputFormat` to use the experimental Pravega batch client.
- Expand current IT tests for the input format. The tests now additionally cover the following verifications: 1) reading multiple streams with batch, 2) multiple passes, and 3) rewinds input format in case of failures.
- Previous configuration of the input format such as `startReadTimestamp` and `eventReadTimeout` is removed, since they are no longer relevant / useful after switching to the batch client.
This PR closes #65 and #56.
As discussed in #65 and #56, the use of reader groups / the `EventStreamReader` API does not work well in batch scenarios, which only allows Pravega segments to be read sequentially. There's also the problem that residual …

[issue-65] Rework FlinkPravegaInputFormat to use batch client

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaInputFormat.java

Closes #100.
- Update pravega dependency
- Update calls to `BatchClient::readSegment` to not pass `endOffset` (see pravega/pravega#2215)

[issue-100] updated Pravega dependency to commit 769a6186

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/main/java/io/pravega/connectors/flink/util/StreamId.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java

Modified checkpoint state for the `FlinkPravegaWriter` to include scope and stream along with the transaction id.
To recover right context/state information during `restoreState` API call.  Closes #74 .
Earlier only transaction ID was stored as checkpoint state and now the state information will have both scope and stream name along with the transaction id.
Running the `FlinkPravegaWriterITCase->testExactlyOnceWriter` should trigger restoreState and the writer instance should be created using stream/scope information from the state object and will be used to commit any pending transactions.

[issue-74] added scope/stream context to checkpoint state for recovering right context

---

build.gradle
src/test/resources/logback.xml

Added file based logging option for the connector test module
To support file based logging in addition to the stdout logging. Closes #25 .
when the connector test module is running, the test logs are recorded in `connector-test.log` file under the root project location.
run `./gradlew clean build` and it will generate `connector-test.log` file under the root project location which will have the test outputs.

[issue-25] added logback configuration for tests to write to both file and stdout

---

src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java

- Adjust SetupUtils to use embedded or external Pravega based on `pravega.uri` system property.
Closes #106.
- When iterating on integration tests, it is handy to reuse a Pravega server across runs, and to reduce the amount of logging output that would otherwise be produced by the embedded Pravega server.

[issue-106] Support for external Pravega in tests

---

build.gradle
src/main/java/io/pravega/connectors/flink/PravegaInputSplit.java

Updated connector build to use latest Pravega and resolved the minor API changes introduced in Pravega that was causing connector build to fail
To fix the build error
Tested `./gradlew clean build` for both direct dependency (submodule) and indirect reference (by passing a specific Pravega artifact reference `-PpravegaVersion` that was published recently) and confirmed that build is passing

[issue-120] updated pravega submodule version and fixed breaking API changes

---

src/main/java/io/pravega/connectors/flink/PravegaConfig.java
src/test/java/io/pravega/connectors/flink/PravegaConfigTest.java

Signed-off-by: Eron Wright <eronwright@gmail.com>
- `PravegaConfig::withDefaultScope` applies with lower priority than other sources
Closes #139
`PravegaConfigTest`

[issue-139] Fix precedence of scope parameter in `PravegaConfig`

---

.travis.yml

*Change log description**
Added conditional check to ensure not to trigger publishing for every pull request. This fix addresses the issue https://github.com/pravega/flink-connectors/issues/141
To enable snapshot publishing only on stable master builds
It enables snapshot build stage only when the branch is master and it's not of pull request type
Travis publishing should not happen for any PRs but only after the PR has been merged to master

[issue-141] updated travis configuration for snapshot publishing

---

build.gradle
gradle.properties
settings.gradle
src/test/java/io/pravega/connectors/flink/PravegaConfigTest.java

This PR addresses the issue https://github.com/pravega/flink-connectors/issues/131
- enabled build configuration to draw Pravega artifacts from jcenter
- enabled option to allow Pravega source dependency (sub-module) in place of snapshots
- To allow connector to draw Pravega artifacts/snapshot dependencies from central repository 
- allows connector build to resolve Pravega artifacts either from snapshot repo or source dependency
- run `./gradlew clean build` to draw Pravega snapshots from jcenter
- run `./gradlew clean build -PusePravegaVersionSubModule=true` to use Pravega that is part of sub-module

[issue-131] Remove pravega source dependency and use SNAPSHOT release versions

---

gradle.properties
src/main/java/io/pravega/connectors/flink/PravegaInputSplit.java

- Fixed segment number breaking API changes introduced in Pravega https://github.com/pravega/pravega/commit/60a2344945f5d9cb68fc497f5e80b79cd013286e
- Updated pravega version to latest snapshot
To fix https://github.com/pravega/flink-connectors/issues/152
Updated the API call from `getSegmentNumber()` to `getSegmentId()`
Run `./gradlew clean build` and make sure test cases pass

[issue-152] Fix segment number API change introduced in Pravega

---

gradle.properties
src/main/java/io/pravega/connectors/flink/AbstractStreamingWriterBuilder.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java

* removed scale grace period configuration for the transaction writer
* updated pravega snapshot version (source and binary) dependency
To address https://github.com/pravega/flink-connectors/issues/154
removed passing transaction scale grace period configuration
`./gradlew clean build` and make sure the tests pass

[issue-154] Remove scale grace period for the writer

---

README.md
gradle.properties
gradle/bintray.gradle
gradle/checkstyle.gradle
gradle/findbugs.gradle
gradle/idea.gradle
gradle/jacoco.gradle
gradle/java.gradle
gradle/maven.gradle
gradlew
gradlew.bat
settings.gradle

- added missing apache license copyright headers to the some of the files
To addresses https://github.com/pravega/flink-connectors/issues/149
No changes to the code
run `./gradlew clean build` and make sure it works

[issue-149] Added missing Apache License copyright headers

---

src/main/java/io/pravega/connectors/flink/AbstractStreamingWriterBuilder.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterITCase.java

This PR addresses the issue https://github.com/pravega/flink-connectors/issues/126
- The transaction timeouts are updated to use the maximum defaults of Pravega
- To avoid flink app from failing due to larger transaction timeouts
- configures default timeouts when the value is not supplied

[issue-126] Update default transaction timeouts in FlinkPravegaWriter to sync with Pravega defaults

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java

Signed-off-by: Eron Wright <eronwright@gmail.com>
- Use single threaded executor in FlinkPravegaWriter
Avoid wasting threads when a single thread will suffice.  Closes #66.
Reduces the non-transactional writer's thread pool size from 5 to 1.
- FlinkPravegaWriter

[issue-66] Use single threaded executor in FlinkPravegaWriter

---

gradle.properties

This PR closes https://github.com/pravega/flink-connectors/issues/158
* updated pravega and connector version to 0.4.0-SNAPSHOT
* updated pravega submodule to latest pravega master commit (0.4.0-SNAPSHOT)
In preparation of connector 0.3.0 release
It is build configuration change to use 0.4.0 snapshots
./gradlew clean build

[issue-158] Update version info from master branch (release-prep 0.3.0)

---

gradle/maven.gradle

updated maven publishing build configuration to add developer info to generated pom file
To address https://github.com/pravega/flink-connectors/issues/167
build configuration changes
run ./gradlew build and see if the generated pom file contains the developer information

[issue-167] Add developer information to pom file for maven publishing

---

build.gradle
gradle/java.gradle

- added distribution task to the build script
To address the issue https://github.com/pravega/flink-connectors/issues/168
- added new build task to assemble release artifacts to a specific directory location
run `./gradlew clean distribution` and verify the release artifacts under `$buildDir/distributions`

[issue-168] Add distribution publishing configuration

---

build.gradle
gradle.properties
src/test/java/io/pravega/connectors/flink/FlinkPravegaInputFormatITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderITCase.java
src/test/java/io/pravega/connectors/flink/utils/ThrottledIntegerWriter.java

- bumped flink version from 1.4.0 to 1.6.0
- dropped `flink-streaming-contrib` reference (FLINK-8175)
To address https://github.com/pravega/flink-connectors/issues/170
build script changes
make sure the build and integration test works by running `./gradlew clean build`

[issue-170] Update connector to support Flink 1.6.0

---

gradle.properties
src/main/java/io/pravega/connectors/flink/AbstractReaderBuilder.java
src/main/java/io/pravega/connectors/flink/AbstractStreamingReaderBuilder.java
src/main/java/io/pravega/connectors/flink/AbstractStreamingWriterBuilder.java
src/main/java/io/pravega/connectors/flink/AbstractWriterBuilder.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderSavepointITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java
src/test/java/io/pravega/connectors/flink/utils/StreamSourceOperatorTestHarness.java

* Added support to draw reader group metrics for FlinkPravegaReader
* Following metrics are enabled
- reader group name
- scope
- stream names
- online readers
- segment positions
- unread bytes
Fixes #31
To publish reader group metrics
Publishes the runtime stats of the reader group as Flink metrics
- On a running Flink cluster alongside with Pravega, run a job that uses `FlinkPravegaReader`  (e.g., anomaly-samples application) and verify if the metrics are visible from UI as well as REST API
```
curl -i -s -f localhost:1028/jobs/2c248d6fe8ed518e959989889a3c5ced/vertices/bc764cd8ddf7a0cff126f51c16239658/metrics?g …
```

[issue-31] Implement connector metrics

---

gradle.properties

* updated connector and pravega version to 0.3.2
* updated pravega sub-module commit to pravega v0.3.2 latest commit
To address https://github.com/pravega/flink-connectors/issues/188
build configuration changes to use appropriate Pravega version

[issue-188] Update Connector version to 0.3.2

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaTableSource.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaTableITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaTableSourceTest.java

added processing and event time support to table source connector
To address the issue https://github.com/pravega/flink-connectors/issues/146
Implements `DefinedProctimeAttribute` and `DefinedRowtimeAttributes` and enables API to supply the processing and event time capabilities to the table source connector
added integration test `FlinkPravegaTableITCase` to verify the implementation.

[issue-146] Support timestamp rows with FlinkPravegaTableSource

---

src/test/java/io/pravega/connectors/flink/FlinkPravegaTableSourceTest.java

Signed-off-by: Flavio Junqueira (fpj) <flavio.junqueira@emc.com>
* Fixes compilation error due to redundant declaration in the `testBatchTableSource` test case.
Fixes #192 
Removes a redundant variable declaration in `testBatchTableSource`.
Build.

[issue 192] Compilation error due to redundant variable declaration

---

gradle.properties
src/main/java/io/pravega/connectors/flink/FlinkPravegaInputFormat.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaOutputFormat.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/main/java/io/pravega/connectors/flink/util/FlinkPravegaUtils.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaOutputFormatTest.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java
src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java

Updated connector code to fix the deprecated API build error because of the recent changes introduced in Pravega client API.
To address the issue https://github.com/pravega/flink-connectors/issues/201
- Updated Pravega artifact and submodule version to latest snapshot
- Addressed the Pravega client API refactoring changes. 
- Fixed unit/integration tests.

[issue-201] Update connector to support Pravega client API refactor

---

build.gradle
gradle.properties
src/main/java/io/pravega/connectors/flink/FlinkPravegaTableFactoryBase.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaTableSource.java
src/main/java/io/pravega/connectors/flink/Pravega.java
src/main/java/io/pravega/connectors/flink/PravegaValidator.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaTableFactoryTest.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaTableITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaTableSinkTest.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaTableSourceTest.java
src/test/java/io/pravega/connectors/flink/FlinkTableITCase.java

- updated Flink version from `1.6.0` to `1.7.2`
- updated Flink scala version from `2.11` to `2.12`
- fixed table API compatibility issues
To address https://github.com/pravega/flink-connectors/issues/213
updated flink version for the connector and resolved table API compatibility issues
SQL client interaction with Pravega should succeed

[issue-213] Fix table API changes addressed for Flink 1.7

---

gradle/java.gradle

* changed archive base name to derive scala version label from gradle properties
To address https://github.com/pravega/flink-connectors/issues/226
fixes the connect artifact label to represent correct scala version support 
`./gradlew clean install` should produce connector artifact to local maven cache with the name `pravega-connectors-flink_2.12*.jar`

[issue-226] Fix incorrect artifact version label

---

src/test/resources/logback.xml

- fixed log4j configurations of test module to suppress unwanted logging
To address https://github.com/pravega/flink-connectors/issues/224
Turned off logging for the packages that are creating more noise and not useful in the context of debugging
./gradlew clean build should produce log output which is readble

[issue-224] Fix unwanted logging in system test

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderRGStateITCase.java
src/test/java/io/pravega/connectors/flink/ReaderCheckpointHookTest.java
src/test/resources/logback.xml

* implemented reset method in reader hook to reset readergroup upon failure/restart
To address https://github.com/pravega/flink-connectors/issues/89
It resets the ReaderGroup to initialize from readergroup config that was passed to the job (upon failure restart, when there is no successful checkpoint taken by Flink).

[issue-89] FlinkPravegaReader fails to achieve exactly-once semantics in some cases

---

src/main/java/io/pravega/connectors/flink/AbstractStreamingReaderBuilder.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java

* enabled reader to accept maximum outstanding checkpoint request parameter
To address https://github.com/pravega/flink-connectors/issues/228
Made changes to `FlinkPravegaReader` builder to accept the maximum outstanding checkpoint request parameter to be used by the `ReaderGroupConfig` 

[issue-228] Allow configuring maximum outstanding checkpoint request

---

src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterITCase.java
src/test/java/io/pravega/connectors/flink/ThrottledIntegerGeneratingSource.java

* updated source simulator to wait for few more checkpoints to finish before closing down
To address the issue https://github.com/pravega/flink-connectors/issues/134
The source simulator waits for the few number of checkpoint operations to complete giving enough time for the sink operator to commit the ongoing transaction.
./gradlew clean build should not fail for the `testExactlyOnceWriter` test case

[issue-134] FlinkPravegWriterITCase testExactlyOnceWriter fails randomly

---

gradle.properties

* Pravega version bumped to 0.6.0-50.51c766c-SNAPSHOT
Fixes https://github.com/pravega/flink-connectors/issues/241
updates the Pravega version from both gradle configuration as well as the sub-module

[issue-241] Update Pravega version to latest master

---

gradle.properties
src/test/java/io/pravega/connectors/flink/FlinkPravegaOutputFormatTest.java

- Updated Pravega version to 0.5.0-2269.6f8a820-SNAPSHOT
Fixes https://github.com/pravega/flink-connectors/issues/245
bumped Pravega version to the latest from Pravega `r0.5` branch in preparation of `r0.5` release

[issue-245] Update Pravega version in r0.5 branch

---

gradle.properties

* update pravega version to 0.5.0-2300.352da54-SNAPSHOT
* update pravega submodule commit to 352da549e729cadf49b88c043d6acd4818045f33
Fixes https://github.com/pravega/flink-connectors/issues/250
Pravega version from gradle properties is updated to latest r0.5 snapshot artifact 

[issue-250] Update Pravega version in r0.5

---

gradle.properties
src/test/java/io/pravega/connectors/flink/FlinkPravegaOutputFormatTest.java

Pravega version bumped to 0.6.0-50.f6fe3a4-SNAPSHOT
Fix failed tests.
Fixes #261 
Updates the Pravega version from both gradle configuration as well as the sub-module
Updates the tests with a new `clientFactory` to avoid `RetriesExhaustedException` 

[issue-261] Update to Pravega 0.6

---

gradle.properties

- Updated Pravega and Connector version to `0.5.1`
- Updated Pravega sub-module commit to `v0.5.1`
Fixes #267 
gradle.properties and Pravega sub-module configuration changes

[issue-267] Update Connector version to 0.5.1

---

gradle.properties

Update connector version to `0.5.2-SNAPSHOT`
Fixes #269

[issue-269] Update connector version to 0.5.2-SNAPSHOT

---

gradle.properties

Pravega version bumped to `0.6.0-50.cd6bfe7-SNAPSHOT`
Fixes #261
Updates the Pravega version from both gradle configuration as well as the sub-module

[issue-261] Update to latest Pravega 0.6

---

.travis.yml
build.gradle
gradle/java.gradle

- Change the `archiveBaseName` of the project
- Add more travis build branches
Supporting multiple versions of Apache Flink. 
After this is merged into master, we will create `r0.6-flink1.7` and `r0.6-flink1.8` branch to support Flink 1.7 and 1.8. The master will always be tracking the latest Flink release and the upcoming Pravega release. I'll raise a PR for Flink 1.9 connector into master. 
Future pull requests should target to `master` branch first if the issue is not related to a specific Flink version. We'll then cherrypick it into other release branches.
Change `archiveBaseName` by adding a MajorMinor version of Flink in the middle.
Allow all Flink versions release branches into the travis build.
**How to …

[issue-263] Supporting multiple versions of Apache Flink

---

gradle.properties

Updates to latest Pravega Client version that includes commit `2acdc6` that fixes the Pravega Client to use the system TrustStore if no trust store is supplied by the user.
Without this fix to Pravega Client the user MUST supply a TrustStore even if Pravega is using SSL certificates that would be trusted by the system trust store.  This impacts the usability of the connector in certain scenarios.

Update To Pravega Version 0.6.0-50.fdc5698-SNAPSHOT

---

.travis.yml
gradle.properties
gradle/java.gradle
src/main/java/io/pravega/connectors/flink/AbstractStreamingReaderBuilder.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaJsonTableSource.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaTableFactoryBase.java
src/main/java/io/pravega/connectors/flink/Pravega.java
src/main/java/io/pravega/connectors/flink/util/ConnectorConfigurations.java
src/main/java/io/pravega/connectors/flink/watermark/AssignerWithTimeWindows.java
src/main/java/io/pravega/connectors/flink/watermark/LowerBoundAssigner.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaInputFormatITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderRGStateITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderSavepointITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaTableSourceTest.java
src/test/java/io/pravega/connectors/flink/utils/ThrottledIntegerWriter.java

Same as the pull request #274 for `r0.6-flink1.7`, the `master` branch require only merging PRs rather than cherry-picking, I create this PR for the master branch.
Same as PR #274 , modified only 
- Change `ClosureCleaner.clean(obj, bool)` which is removed since Flink 1.8 into `ClosureCleaner.clean(obj, ExecutionConfig.ClosureCleanerLevel.RECURSIVE, bool)`
- Change `TableValidationUtil` which is removed since Flink 1.9 into `TableSourceValidation`

[issue-265] Reader side: Implement watermark with Pravega (for master branch aka. Flink 1.9)

---

src/main/java/io/pravega/connectors/flink/AbstractStreamingWriterBuilder.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaTableFactoryBase.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/main/java/io/pravega/connectors/flink/Pravega.java
src/main/java/io/pravega/connectors/flink/PravegaValidator.java
src/main/java/io/pravega/connectors/flink/util/ConnectorConfigurations.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaTableSinkTest.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java
src/test/java/io/pravega/connectors/flink/FlinkTableITCase.java
src/test/java/io/pravega/connectors/flink/ThrottledIntegerGeneratingSource.java
src/test/java/io/pravega/connectors/flink/utils/FailingMapper.java
src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java

Same as the pull request #277 for r0.6-flink1.7, the master branch require only merging PRs rather than cherry-picking, I create this PR for the master branch.
Same as PR #277 , modified only
- Change from `Types.Long` to `Types.Timestamp` in `testStreamTableSinkUsingDescriptorWithWatermark` to get the test pass.

[issue-266] Writer side: Implement watermark with Pravega (for master branch aka. Flink 1.9)

---

gradle.properties
src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java
src/test/java/io/pravega/connectors/flink/ReaderCheckpointHookTest.java

Change checkpoint scheduler from one-per-checkpoint to a long-lived executorService
Bump pravega version to `0.6.0-50.5a60e36-SNAPSHOT`
Change implementation in `ReaderCheckpointHook` and fix tests in `ReaderCheckpointHookTest`
Change to a long-lived executorService to prevent the `ScheduledExecutorService` shutdown too early.
`./gradlew clean build` should pass.

[issue-282] Recover failed by Pravega checkpoint failure

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java

- Don't emit a final watermark in the reader
Closes #288 
Remove the final watermark emit after the source is running

[issue-288] Don't emit a final watermark when source is stopped

---

gradle.properties

- Update connector version to `0.6.1-SNAPSHOT`
Fixes #291 

[issue-291] Update connector version to 0.6.1-SNAPSHOT

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java

- Remove `getStreamNames` call when calculating Watermark
Fixes #299 
Move call to calculate Stream into `PeriodicWatermarkEmitter` constructor
Target to master, should cherry-pick to all `0.7` and `0.6` branch

[issue-299] Remove getStreamNames call when calculating Watermark

---

src/main/java/io/pravega/connectors/flink/AbstractStreamingWriterBuilder.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java

- Force transaction timeout to be greater than 10 seconds
Fixes #298 
Change the default txn timeout in mock sink function from `30ms` to `30s` 
Target to master, should cherry-pick to all `0.7` and `0.6` branch

[issue-298] Fix tests that transaction timeout should be greater than 10 seconds

---

build.gradle
gradle.properties

- Bump the Pravega version and submodule to the latest `0.6.1-rc`
Fixes #300 
Update `gradle.properties` and submodule
Target to master, should cherry-pick to all `0.6` branch

[issue-300] Prepare for 0.6.1 release

---

build.gradle
gradle.properties

- Prepare for the `0.6.1` release
Fix #300 
Remove the temp maven repository and update the connector version into `0.6.1`
Target to `r0.6`, should cherry-pick to all `0.6` branch

[issue-300] Prepare for the 0.6.1 release

---

src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java
src/test/java/io/pravega/connectors/flink/ReaderCheckpointHookTest.java

* Deleted the depcreated resetReadersToCheckpoint API
* modified ReaderCheckpointHookTest.java
fix #304
* Deleted the depcreated `resetReadersToCheckpoint API`, use `resetReaderGroup#ReaderGroupConfig` instead 
*  New API needs CheckpointImpl to be added to Checkpoint
reference: [ReaderGroupConfigTest](https://github.com/pravega/pravega/blob/195f247cdfd8168c427ab76fb2040c5ae4689438/client/src/test/java/io/pravega/client/stream/ReaderGroupConfigTest.java)

[issue-304] Remove deprecated resetReadersToCheckpoint API

---

src/test/java/io/pravega/connectors/flink/ReaderCheckpointHookTest.java

* `ReaderCheckpointHookTest.java`
fix #313 
The default value of `groupRefreshTimeMillis` and `maxOutstandingCheckpointRequest` is not set in ReaderGroupConfig, but set in ReaderGroupConfigBuilder. So the original test code will raise an ZeroValueError.
So Instead of using mock(ReaderGroupConfig.class) to init a ReaderGroupConfig instance, 
we can use ReaderGroupConfigBuilder to build a ReaderGroupConfig instance with `maxOutstandingCheckpointRequest` and  `groupRefreshTimeMillis` default values.
`./gradlew clean build ` should pass

[issue-313] Fix-testRestore-bug

---

gradle.properties
src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java

- Bump the Pravega version and fix compile errors
Fixes #316 
Update `gradle.properties` and submodule
Delete the scope and stream settings in the `StreamConfiguration` builder
Target to master, should cherry-pick to all `0.7` branch

[issue-316] Update Pravega version to latest master

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java

- Handle TruncatedDataException in the reader
Fixes #319 
Let the reader call `readNextEvent` again when catching `TruncatedDataException`
Add tests to verify the exception is caught and read can go on as nornal
Target to master, should cherry-pick to all `0.7` and `0.6` branch

[issue-319] Handle TruncatedDataException in the reader

---

gradle.properties

- Prepare for the `0.6.2` release
Fix #326 
Update the connector version into `0.6.2`
Update the Pravega client version into `0.6.2`
Target to `r0.6`, should cherry-pick to all `0.6` branch

[issue-326] Prepare for 0.6.2 release

---

gradle.properties
src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/util/FlinkPravegaUtils.java

- Make the reader name valid
Fixes #323 , remain only the legal characters in `readerId`.
Bump up the pravega version to the latest master
Removed the unused `getDefaultReaderName` function.
Create a `getReader` function to remove the illegal characters in the reader id.
e.g.
```
Source: Custom Source -> Map -> Map -> Sink: Unnamed (1/1)
```
Changes into
```
Pravega-reader-for-SourceCustomSource-Map-Map-SinkUnnamed-1-1
```
Target to master, should cherry-pick to all `0.7` branch

[issue-323] Make the reader name valid

---

gradle.properties

Update connector version to `0.6.3-SNAPSHOT`
Fixes #328 
Target to `r0.6`, should cherry-pick to all `0.6` branch

[issue-328] Update Connector version to 0.6.3-SNAPSHOT

---

documentation/src/docs/serialization.md
src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/serialization/JsonSerializer.java
src/main/java/io/pravega/connectors/flink/serialization/PravegaDeserializationSchema.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java
src/test/java/io/pravega/connectors/flink/utils/IntegerSerializer.java
src/test/java/io/pravega/connectors/flink/utils/IntegerWithEventPointer.java
src/test/java/io/pravega/connectors/flink/utils/JSONSerializer.java

- [issue-180] Provide method for deserialization with metadata
Fixes #180 
Provide a method `deserializeWithMetadata` for user to override that can leverage `EventRead` in the deserialization.
Added unit test for the case.
Target to master, should cherry-pick to all `0.7` branch

[issue-180] Provide method for deserialization with metadata

---

src/main/java/io/pravega/connectors/flink/AbstractStreamingReaderBuilder.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java

- Make connector Generated ID consistent among checkpoints
Fixes #331 
- Removed the stream cuts info in `generateUid` function because checkpoint restore will change the starting streamcut
- Changed unit tests for `generateUid`
`./gradlew clean build` passes. 
Target to master, should cherry-pick to all `0.7` branch

[issue-331] Make connector Generated ID consistent among checkpoints

---

documentation/src/docs/streaming.md

**1. Changes under"FlinkPravegaReader" section:**
- "Parallelism" -> "Reader Parallelism";
- "Timestamp Extraction / Watermark Emission" -> "Timestamp Extraction (Watermark Emission)";
**2. Changes under"FlinkPravegaWriter" section:**
- "Parallelism" -> "Writer Parallelism";
Some anchor links within "Steaming Connector" page's table of contents were working in GitHub, but weren't in pravega.io. The invalid anchor links are listed within "Change Log Description".
- ["Streaming Connector" page on pravega.io](http://pravega.io/connectors/flink/docs/latest/streaming)
- ["Streaming Connector" page on GitHub](https://github.com/pravega/flink-connectors/blob/master/documentation/src/docs/streaming.md)
The changes should make the anchor links …

[issues-338] Streaming Connector TOC invalid anchor links

---

src/main/java/io/pravega/connectors/flink/watermark/LowerBoundAssigner.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java

- Change the code of `LowerBoundAssigner` so that it doesn't subtract one from the lower bound to determine the watermark
- Change the test code corresponding to `LowerBoundAssigner`
Fix #343 
Flink treats the watermark in an inclusive manner, so the -1 subtraction should be removed to comply with that expectation.

[Issue-343] Inclusive vs. Exclusive Watermarks

---

src/main/java/io/pravega/connectors/flink/watermark/LowerBoundAssigner.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java

- Remove trivial comments at `FlinkPravegaReaderTest.java`
- Change improper comments at `LowerBoundAssigner.java`
Fix #350 
Make the codes more clear.
`./gradlew clean build` should pass.

[issue-350] Remove trivial comments and change improper comments

---

src/main/java/io/pravega/connectors/flink/watermark/LowerBoundAssigner.java

`io.pravega.connectors.flink.watermark.LowerBoundAssigner`
After we fixed #343, we can directly return new Watermark(timeWindow.getLowerTimeBound()) instead of having check.
Fixes #366 

[issue-366] Remove check in getWatermark.

---

gradle.properties

Update the dependency and submodule to the latest commit `5314cfd`.
Fixes #368 
Update the 0.8 connector to the latest Pravega client to include the fix https://github.com/pravega/pravega/pull/4767.
Target to `master`, should cherry-pick to all `0.8` branches

[issue-368] Ensure BatchClient not escaping null pointer exception

---

src/main/java/io/pravega/connectors/flink/PravegaConfig.java
src/test/java/io/pravega/connectors/flink/PravegaConfigTest.java

`PravegaConfig.withDefaultScope`
`PravegaConfigTest.java `
Fixes #374 
remove `if (this.defaultScope == null)` to make sure override the default scope is possible.

[Issue-374] withDefaultScope bugfix

---

gradle.properties

Signed-off-by: Guangfeng Xu <Guangfeng.Xu@dell.com>
Prepare for the 0.7.1 release
Fix #371 
Update the connector version into 0.7.1
Update the Pravega client version into 0.7.1

[issue-371] Prepare for 0.7.1 release

---

.codecov.yml

Adds a `.codecov.yml` file to set the project check threshold to allow 20% drops in coverage.
Fixes #394 Allow drops in percentage of coverage checks.
Allows 20% drops in coverage.
This PR's project check should pass even though this branch is failing in another PR.

Issue 394: Increase Codecov project check threshold

---

gradle.properties

Signed-off-by: Brian Zhou <b.zhou@dell.com>
Update the Pravega to the latest version before 0.8
Fixes #403 
Update both the dependency and the submodule to commit 279ac21
Should cherry-pick to all `0.8` branches

[issue-403] Update the Pravega to the latest version before 0.8

---

src/main/java/io/pravega/connectors/flink/util/ConnectorConfigurations.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaTableFactoryTest.java

Add check for Dynamic-loading credentials for Pravega in Table API
Fixes #409 
Check for the value of the env variable `pravega.client.auth.loadDynamic` and system property `pravega_client_auth_loadDynamic` to decide if we keep the credential as `SimpleCredentials`.

[issue-409] Fix Dynamic-loading credentials for Pravega client in Table API

---

src/main/java/io/pravega/connectors/flink/util/FlinkPravegaUtils.java
src/test/java/io/pravega/connectors/flink/util/FlinkPravegaUtilsTest.java

Add a check and truncate for too-long task name to generate reader ID.
Fixes #413 
Pravega client 0.8 added a length check of 256 of the reader ID. But in SQL use cases, there will be long SQL queries to be the task name for the reader, which may violate this check. Add a check and truncate for too-long task name to generate reader ID.
`./gradlew clean build ` passes

[issue-413] Ensure the reader name below the length limit

---

gradle.properties

- Updated Pravega and Connector version to `0.8.0`
- Updated Pravega sub-module commit to `v0.8.0`
Fixes #411 
`gradle.properties` and Pravega sub-module configuration changes

[issue-411] Prepare for 0.8.0 release

---

gradle.properties

Update connector version to `0.8.1-SNAPSHOT` in branch `r0.8`
Fix #417  

[issue-417] Update connector version in branch r0.8

---

gradle.properties
src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java

- Update Pravega to use submodule to pick up the fix needed (https://github.com/pravega/pravega/pull/5226)
- Retry close when InterruptedException is caught in Pravega reader
- Record the last exception in close method and throw it 
Fixes #416 
A "cleaner" close for `FlinkPravegaReader`
Tested locally with Flink and Pravega standalone cluster with reader application, no more GRPC threads after the job cancel.
Target to `r0.8` now, should cherry-pick to all `0.8` branches.

[issue-416] Retry close when InterruptedException is caught in Pravega reader

---

gradle.properties
src/main/java/io/pravega/connectors/flink/PravegaConfig.java
src/main/java/io/pravega/connectors/flink/util/FlinkPravegaUtils.java
src/test/java/io/pravega/connectors/flink/PravegaConfigTest.java
src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java

- Update Pravega version to `0.9.0-2705.09f82eb-SNAPSHOT`
- Bump the sub-module commit to `09f82eb`
- Change the credential package (Caused by https://github.com/pravega/pravega/commit/0e77c81a09a2f6019499259de7fa002398a3dc90)
- Turn off the secure ZK (Caused by https://github.com/pravega/pravega/commit/c0378e3ace4ae819c065cfa59c1bb0926fedbf4c)
Fixes #428 
Update Pravega version to the latest and fix compatibility issues

[issue-428] Update Pravega version to the latest

---

.codecov.yml
src/main/java/io/pravega/connectors/flink/AbstractReaderBuilder.java
src/main/java/io/pravega/connectors/flink/AbstractStreamingReaderBuilder.java
src/main/java/io/pravega/connectors/flink/AbstractStreamingWriterBuilder.java
src/main/java/io/pravega/connectors/flink/AbstractWriterBuilder.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaInputFormat.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaOutputFormat.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaTableSink.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/main/java/io/pravega/connectors/flink/PravegaConfig.java
src/main/java/io/pravega/connectors/flink/serialization/WrappingSerializer.java
src/main/java/io/pravega/connectors/flink/table/descriptors/Pravega.java

Signed-off-by: Brian Zhou <b.zhou@dell.com>
- Fix all javadoc "no return" warnings
Fixes #370 
- Fix all javadoc no return warnings
- Adjust the code coverage constraint.
Should cherry-pick to all `0.9` branches.

[issue-370] Fix all javadoc "no return" warnings

---

src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterITCase.java
src/test/java/io/pravega/connectors/flink/dynamic/table/FlinkPravegaDynamicTableITCase.java

Change FlinkPravegaDynamicTableITCase to use a single segment.
This integration test appears to be using watermarks in a way that is dependent on the order in which events are written across routing keys. Since the order across routing keys is not guaranteed by Pravega, this causes the test to fail intermittently. 
Fixes #452 
The change in this PR changes the number of segments from 3 to 1, avoiding ordering issues. Proper ordering and watermarking should be tested as part of a different integration test.
```
./gradlew build
```

Change FlinkPravegaDynamicTableITCase to use a single segment

---

src/main/java/io/pravega/connectors/flink/AbstractStreamingWriterBuilder.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaOutputFormat.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/main/java/io/pravega/connectors/flink/table/descriptors/Pravega.java
src/main/java/io/pravega/connectors/flink/util/FlinkPravegaUtils.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaOutputFormatTest.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java

- Make event router optional
Fixes #433 
Make event router nullable for `FlinkPravegaWriter` and `FlinkPravegaOutputFormat`, and use random routing to write data when event router is null.

[issue-433] Make event router optional

---

build.gradle
checkstyle/import-control.xml
src/main/java/io/pravega/connectors/flink/PravegaConfig.java
src/main/java/io/pravega/connectors/flink/serialization/DeserializerFromSchemaRegistry.java
src/main/java/io/pravega/connectors/flink/serialization/JsonSerializer.java
src/main/java/io/pravega/connectors/flink/util/SchemaRegistryUtils.java

Make schema registry dependencies optional and clean up the dependencies
Fixes #440 
- Make schema registry dependencies optional by moving the related logic to a new class `SchemaRegistryUtils`
- Fixes the missing `schemaRegistryUri` check in the `equals` and `hashcode` function of `PravegaConfig`
- Clean up the dependency list, remove some redundant dependencies
- Clean up the showdowOnly list, this one is going to the pom file.
Target to master, should only cherry-pick to `r0.9-flink1.10` branch

[issue-440] Make schema registry dependencies optional and clean up

---

src/main/java/io/pravega/connectors/flink/AbstractStreamingWriterBuilder.java

Signed-off-by: Charlie <Charlie.L.Chen@dell.com>
Increase the default transaction lease renewal time to 120 seconds
Fixes #455 
Set `DEFAULT_TXN_LEASE_RENEWAL_PERIOD_MILLIS` = 120000

[Issue-455] Increase the default transaction lease renewal time to 120s

---

gradle.properties
src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java
src/test/java/io/pravega/connectors/flink/ReaderCheckpointHookTest.java

Signed-off-by: Charlie <Charlie.L.Chen@dell.com>
Upgrade pravega version and submodule to the latest commit pravega/pravega@2515791
Remove the readerGroupId specification which is no longer needed in resetReaderGroup() call in ReaderCheckpointHook
Fixes #457 
1. Upgrade pravega version and submodule to the latest commit pravega/pravega@2515791
2. Remove the readerGroupId specification in ReaderCheckpointHook
`gradlew build` passes

[Issue-457] Upgrade Pravega to the latest 0.9

---

gradle/maven.gradle

Change `singleSignature` to `signatures` in `gradle/maven.gradle` for signing the dependencies
Fix #464 
`gradle/maven.gradle` changes

[issue-464] Change singleSignature to signatures

---

src/main/java/io/pravega/connectors/flink/EventTimeOrderingFunction.java
src/main/java/io/pravega/connectors/flink/dynamic/table/FlinkPravegaDynamicTableSink.java

In the new table sink, the non null fields cannot be specified as a routing key filed.
It is caused by the check
```java
checkArgument(DataTypes.STRING().equals(fieldTypes[keyIndex]), "Key field must be of type 'STRING'");
```
Comparing on DataType level is not correct in this case, we need to check if the logical type root is `CHAR` or `VARCHAR` to determine if it is a string or not.
Fixes #481 
Check the type's root so both string and other string-like type like `CHAR` and `VARCHAR` could pass the check.
`./gradlew clean build` passes.

[Issue-481] Row-based router cannot be specified on non-null field

---

.github/workflows/build.yml

A typical name of the artiface should be something like 0.10.0-1.ff9f6d1-SNAPSHOT. With the [version]-[commit count]-[commit sha]-SNAPSHOT format. But for artifacts produced by Github Actions, the commit count are always set to 1. This is caused by the `depth==1` clone, so we change it to unlimited.
Fixes #491 
Add a parameter to specify the clone depth to be unlimited.
Artifacts build by the new yaml should have the corret commit count.
See the `List of artifacts` section of this [run](https://github.com/thekingofcity/flink-connectors/runs/2359587611).

[Issue-491] Wrong count number of the artifact

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/dynamic/table/FlinkPravegaDynamicTableSink.java
src/main/java/io/pravega/connectors/flink/dynamic/table/FlinkPravegaDynamicTableSource.java
src/main/java/io/pravega/connectors/flink/dynamic/table/PravegaOptions.java
src/test/java/io/pravega/connectors/flink/dynamic/table/FlinkPravegaDynamicTableFactoryTest.java

Java 8's Optional was mainly intended for return values from methods, and not for properties of Java classes, as described in [Optional in Java SE 8](https://blog.joda.org/2014/11/optional-in-java-se-8.html):
> > Of course, people will do what they want. But we did have a clear intention when adding this feature, and it was not to be a general purpose Maybe or Some type, as much as many people would have liked us to do so. **Our intention was to provide a limited mechanism for library method return types** where there needed to be a clear way to represent "no result", and using null for such was overwhelmingly likely to cause errors.
>
>The key here is the focus on use as a return type. The class is definitively not intended for use as a property of a Java Bean. …

[Issue-496] best practice of `optional`

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java

- Add transaction timeout support
- Handle unknown transaction error and do not let it escape and fail the job
- Add `toString` method in `PravegaTransactionState`
Fixes #506 
Target to master, should cherry-pick to all `0.10` and `0.9` branch

[issue-506] Improve the transactional writer

---

src/main/java/io/pravega/connectors/flink/serialization/DeserializerFromSchemaRegistry.java

The Schema Registry offers a way to get the serialization format from `GroupProperties`. Flink connector can take advantage of it instead of getting it from `SchemaInfo`.
Fix #510 
Use `getSerializationFormat` to get serialization format from `GroupProperties` instead of from `SchemaInfo`.

[issue-510] Change to get serialization format from GroupProperties

---

checkstyle/import-control.xml
gradle.properties
src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java

In pravega/pravega#6028, the exception thrown has changed from a general `RuntimeException` to a `StatusRuntimeException`, we need to update the Pravega client version and make the change in the transactional writer.
Fixes #514 
Change `RuntimeException` to `StatusRuntimeException`.
`./gradlew clean build` passes.

[Issue-514] Catch the exact exception for checkTransactionStatus

---

.github/workflows/build.yml
build.gradle
gradle.properties
gradle/maven.gradle

Changes the destination for snapshot artifacts from JCenter to GitHub Packages Registry.
Fixes pravega/flink-connectors#507 
Snapshot action from build workflow is updated to publish to GPR:
- It uses auto-generated GITHUB_TOKEN token which is valid only in current repository
- By default publishes to owner/repository which is a repository where the action is executed
- Removes jcenter()/jfrog references from build scripts
- Exclude zookeeper 3.6.2 imported by pravega-standalone and wait for pravega/pravega#6129
Once PR is merged the next build on master branch must produce snapshot artifacts in GPR
**Known Limitations**
- Packages are not …

[issue-507] Publish snapshot artifacts in GitHub packages registry but not in Jcenter

---

.github/workflows/build.yml

Publishing artifacts to Github packages fails with 401.
Fixes #507 
Change publish token to `GITHUB_TOKEN`.
Could publish artifacts to Github packages.

[Issue] undefined fix publish GitHub packages

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/dynamic/table/FlinkPravegaDynamicTableSource.java
src/test/java/io/pravega/connectors/flink/dynamic/table/FlinkPravegaDynamicTableITCase.java

Add format metadata during the deserialization process.
Fixes #534 
Preserve the format metadata keys and push down to the nested deserializationSchema.

[Issue-534] Support format metadata

---

src/main/java/io/pravega/connectors/flink/table/catalog/pravega/PravegaCatalog.java
src/test/java/io/pravega/connectors/flink/formats/registry/PravegaRegistrySeDeITCase.java

Move json related option operations into one function 
Fix #543 
Move json related option operations into `propagateJsonOptions` in `PravegaCatalog`

[issue-543] Generify a common method to deal with Json related options

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/dynamic/table/FlinkPravegaDynamicTableSource.java
src/main/java/io/pravega/connectors/flink/formats/registry/PravegaRegistryRowDataDeserializationSchema.java
src/main/java/io/pravega/connectors/flink/serialization/JsonSerializer.java
src/main/java/io/pravega/connectors/flink/table/catalog/pravega/PravegaCatalog.java
src/main/java/io/pravega/connectors/flink/util/FlinkPravegaUtils.java
src/main/java/io/pravega/connectors/flink/util/SchemaRegistryUtils.java

Prevent the `NullPointerException` if there is no credential after `getSchemaRegistryClientConfig` is called.
Fixes #539 
Remove the authentication process if the pravegaConfig contains no credential.
Tests using SchemaRegistry should pass when the pravega is in the standalone mode and is configured without credentials.
> `FlinkPravegaSchemaRegistryReaderTestITCase.testReaderWithJsonRegistryDeserializer`.

[Issue-539] NullPointerPxception when there is no credentials in pravega client config

---

src/main/java/io/pravega/connectors/flink/formats/registry/PravegaRegistryFormatFactory.java
src/main/java/io/pravega/connectors/flink/formats/registry/PravegaRegistryOptions.java
src/main/java/io/pravega/connectors/flink/formats/registry/PravegaRegistryRowDataSerializationSchema.java
src/main/java/io/pravega/connectors/flink/table/catalog/pravega/PravegaCatalog.java
src/main/java/io/pravega/connectors/flink/table/catalog/pravega/factories/PravegaCatalogFactory.java
src/main/java/io/pravega/connectors/flink/table/catalog/pravega/factories/PravegaCatalogFactoryOptions.java
src/test/java/io/pravega/connectors/flink/PravegaCatalogITCase.java
src/test/java/io/pravega/connectors/flink/formats/registry/PravegaRegistryFormatFactoryTest.java
src/test/java/io/pravega/connectors/flink/formats/registry/PravegaRegistrySeDeITCase.java

Support a new Json option `ENCODE_DECIMAL_AS_PLAIN_NUMBER` in Pravega Registry format factory
Fix #545 
Add new ConfigOption in `PravegaRegistryOptions` and `PravegaCatalogFactory`
Use new `ObjectMapper` configured with `encodeDecimalAsPlainNumber` in serialization schema
`./gradlew clean build` passes.

[issue-545] Support new Json option

---

src/main/java/io/pravega/connectors/flink/table/catalog/pravega/factories/PravegaCatalogFactory.java

Add missing `.` in json prefix in `PravegaCatalogFactory`.
Fix #557 
Fix `JSON_PREFIX` in `PravegaCatalogFactory`

[issue-557] Fix Json prefix

---

build.gradle

Remove `mavenLocal()` in the Gradle build script
Fix #569 
Remove `mavenLocal()` in `build.gradle`

[issue-569] Remove mavenLocal() in the Gradle build script

---

build.gradle
gradle.properties

The current `mkdocsBuild` job will fail after #490 upgraded the Gradle to 7.
Update the plugins to make `mkdocsBuild` great again.
Fixes #581 
Update `build.gradle` and `gradle.properties`.
`.\gradlew clean mkdocsBuild` will generate the desired docs.

[Issue-581] Make `mkdocsBuild` great again

---

build.gradle
src/main/java/io/pravega/connectors/flink/table/catalog/pravega/PravegaCatalog.java
src/main/java/io/pravega/connectors/flink/table/catalog/pravega/factories/PravegaCatalogFactory.java
src/main/java/io/pravega/connectors/flink/table/catalog/pravega/factories/PravegaCatalogFactoryOptions.java
src/test/java/io/pravega/connectors/flink/PravegaCatalogITCase.java
src/test/java/io/pravega/connectors/flink/formats/registry/PravegaRegistrySeDeITCase.java
src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java

- use `ClientConfig` to create `StreamManager` instead of `ControllerURI` when creating `PravegaCatalog` in order to set security configs which can be read from `ClientConfig`
- enable `enableTls`
Fix #577 
Add Pravega security options in Catalog factory options so that we can create `StreamManager` upon `ClientConfig` that contains security configs.
Set `enableTls` to true for integration tests.

[issue-577] Add support for security in PravegaCatalog

---

.gitignore
README.md
documentation/src/docs/index.md
documentation/src/docs/python.md
documentation/src/mkdocs.yml
src/main/python/pravega_config.py
src/main/python/pravega_reader.py
src/main/python/pravega_writer.py

Python is a popular developing language and we can already use the Python Table API to perform Pravega read and write. However, sometimes SQL is not enough, many users still want to use the Python datastream API.
In order to support multiple Flink version, we plan to have a suggested implementation for a python wrapper and users can include in the python project.
Fixes #571 
Add Python API and related docs for the connectors.
*Common Structure of Python DataStream API Programs with Pravega Flink Connectors* mentioned in the doc should work.

[Issue-571] Add Python datastream API support

---

gradle/maven.gradle

-  Allow communication with a repository over an insecure HTTP connection.
Fix #595 
- Set `allowInsecureProtocol` to `true` in `maven.gradle`

[issue-595] Allow insecure HTTP connection

---

build.gradle

- Allow communication with a repository over an insecure HTTP connection.
Fix #597 
- Set `allowInsecureProtocol` to true in `build.gradle`

[issue-597] allow insecure http connection

---

README.md

The current compatibility matrix in README is outdated as we release the connector for pravega 0.10.
Fixes #615 
No code changes, only `README.md` is updated.
Update compatibility matrix to:
| Git Branch | Pravega Version | Java Version To Build Connector | Java Version To Run Connector | Flink Version | Status | Artifact Link |
|-------------------------------------------------------------------------------------|------|---------|--------------|------|-------------------|----------------------------------------------------------------------------------------|
| [master](https://github.com/pravega/flink-connectors) …

[Issue-615] Update the compatibility matrix for 0.11 and 1.14

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaOutputFormat.java
src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
src/main/java/io/pravega/connectors/flink/serialization/FlinkSerializer.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java

The `FlinkSerializer` from `FlinkPravegaWriter` is also needed in the new unified sink API #460.
Fix #620
Instead of nesting it in the `FlinkPravegaWriter`, move it to the `serialization` package.
`.\gradlew clean build` should pass.

[Issue-620] Multiple use of the nested FlinkSerializer

---

src/test/java/io/pravega/connectors/flink/utils/ThrottledIntegerGeneratingSource.java

There is a mismatch in ThrottledIntegerGeneratingSource between code and comment.
Fix #619 
Change the code to `while (this.lastCheckpointConfirmed <= lastCheckpoint + 2) {`.
`.\gradlew clean build` should pass.

[Issue-619] Mismatch in ThrottledIntegerGeneratingSource

---

src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java
src/main/java/io/pravega/connectors/flink/serialization/CheckpointSerializer.java
src/test/java/io/pravega/connectors/flink/ReaderCheckpointHookTest.java

Move `CheckpointSerializer` into package `serialization`.
Fix #627 
- Move `CheckpointSerializer` to package `serialization` and change its visibility
- Change all the affected import path
`FlinkPravegaReaderSavepointITCase` test passed

[Issue-627] Move `CheckpointSerializer` to serialization package

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaInputFormat.java

Change log description
Fix npe when close pravega batch client factory in batch mode
#635 
Purpose of the change
When the batch task is executed, avoid the null pointer exception
What the code does
Add the null condition to avoid calling methods with null values
How to verify it
In the scenario of batch reading Pravega, when the task ends, an NPE exception will be reported

[issue-635] Fix null pointer when closing pravega batch client factory

---

documentation/src/docs/catalog.md

- Address the Schema Registry dependency required to use the Table API and catalog in Pravega catalog document.
Fix #647 
- Address the Schema Registry dependency in Catalog doc

[issue-647] Address extra dependencies in catalog document

---

build.gradle
gradle.properties
src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderSavepointITCase.java
src/test/java/io/pravega/connectors/flink/sink/PravegaEventWriterTest.java
src/test/java/io/pravega/connectors/flink/sink/PravegaTransactionWriterTest.java

Upgrade connector to Flink 1.15
Fix #651 
Upgrade connector to be compatible with these changes.
NOTE THAT SINK IS UPGRADED TO V2. THE CURRENT V1 TEST WILL FAIL AND IS COMMENTED OUT.
* [FLINK-23986](https://issues.apache.org/jira/browse/FLINK-23986) Add support for opting-out of Scala
* [FLINK-24427](https://issues.apache.org/jira/browse/FLINK-24427) Hide Scala in flink-table-planner from API
* [FLINK-25276](https://issues.apache.org/jira/browse/FLINK-25276) FLIP-203: Support native and incremental savepoints
* [FLINK-25555](https://issues.apache.org/jira/browse/FLINK-25555) FLIP-191: Extend unified Sink interface to support small file compaction

[Issue-651] Upgrade Flink to 1.15

---

documentation/src/docs/table-api.md

- Add missing scope specification and scan uid option in the table api document.
Fix #634 
- Add missing options

[issue-634] Add missing options in table api document

---

build.gradle
gradle.properties

Upgrade Pravega version to 0.11
Fix #649 
Update Pravega version to 0.11 and force `io.netty` to `4.1.65.Final` as `pravega-standalone` states it wants `4.1.68.Final` but it doesn't.

[Issue-649] Upgrade pravega to the latest 0.11

---

src/test/java/io/pravega/connectors/flink/dynamic/table/FlinkPravegaDynamicTableFactoryTest.java

- Add required scheme in controller URI in unit test to align with changes in Pravega: https://github.com/pravega/pravega/pull/6559.
- Fix #660 
- Change `CONTROLLER_URI` in unit test `FlinkPravegaDynamicTableFactoryTest` to `tcp://dummy:9090`
`gradlew clean build` should pass

[Issue-660] Add required sceme for controller URI

---

src/main/java/io/pravega/connectors/flink/sink/PravegaSink.java
src/main/java/io/pravega/connectors/flink/source/PravegaSource.java

Add `@Experimental` annotation on the Source and Sink interface to inform the end users.
Fix #676 
Add `@Experimental` annotation to `PravegaSource` and `PravegaSink` class

[Issue-676] Mark new Source and Sink interfaces as Experimental API

---

gradle.properties
src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
src/main/java/io/pravega/connectors/flink/serialization/PravegaDeserializationSchema.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaSchemaRegistryReaderTestITCase.java
src/test/java/io/pravega/connectors/flink/FlinkPravegaSchemaRegistryWriterTestITCase.java

Schema Registry will upgrade the internal Avro to 1.11 which will break the compatibility of the current implementation.
Fix #675 
Remove `withDeserializationSchemaFromRegistry` and use schema-specific `PravegaDeserializationSchema` in `withDeserializationSchema`.

[Issue-675] Keep schema registry up to date

---

build.gradle

The latest Pravega update netty version, so the tests in connectors could remove the force netty version.
Fix #671 
Remove force netty.

[Issue-671] Use Pravega netty in tests

---

gradle.properties

Update connector and Pravega version to `0.11.1-SNAPSHOT`
Fix #680 
Update `connectorVersion` and `pravegaVersion` in `gradle.properties`

[issue-680] Update connector version to 0.11.1-SNAPSHOT on r0.11 branch

---

gradle.properties

Update connector and Pravega version to `0.12.0-SNAPSHOT`, schema registry to `0.5.0-SNAPSHOT`
Fix #679 

[Issue-679] Update connector version to 0.12.0-SNAPSHOT

---

gradle.properties

Update Flink version to `1.14.4` on branch `r0.12-flink1.14` to avoid log4j2 vulnerability during build
Fix #684 
Update `flinkVersion` in `gradle.properties`

[Issue-684] Update Flink version on branch r0.12-flink1.14

---

src/main/java/io/pravega/connectors/flink/table/catalog/pravega/PravegaCatalog.java

Change the usage of deprecated `deleteScope()` API to a new `deleteScopeRecursive()` API as introduced in Pravega 0.11.0(ref: https://github.com/pravega/pravega/pull/6312).
Fix #685 
Change `deleteScope()` to `deleteScopeRecursive()` in `PravegaCatalog`

[Issue-685] Change deprecated usage of `DeleteScope` API

---

README.md
gradle.properties

Update connector and Pravega version to `0.13.0-SNAPSHOT`, schema registry to `0.6.0-SNAPSHOT`
Fix #690 
Update compatibility matrix in `README.md`

[Issue-690] Update connector version to 0.13.0-SNAPSHOT

---

README.md
gradle.properties

Update connector to `0.12.1-SNAPSHOT` on `r0.12` branch
Fix #691  
Update `connectorVersion` in `gradle.properties`
Update compatibility matrix in `README.md`

[Issue-691] Update connector version to 0.12.1-SNAPSHOT on r0.12 branch

---

src/main/java/io/pravega/connectors/flink/source/enumerator/PravegaSplitEnumerator.java

Fix a javadoc warning in `PravegaSplitEnumerator`
Fix #694 
Add `@return` in the javadoc in `PravegaSplitEnumerator`
`gradlew clean build` passed

[issue-694] Fix javadoc warning

---

src/test/java/io/pravega/connectors/flink/utils/DockerImageVersions.java
src/test/java/io/pravega/connectors/flink/utils/runtime/PravegaContainer.java

Signed-off-by: Fan Yang <fan.yang5@emc.com>
Update Pravega and Schema registry docker image versions to the latest release for Integration tests
Fix #696 
Change docker image versions in `DockerImageVersions`

[Issue-696] Update docker image version

---

src/test/java/io/pravega/connectors/flink/utils/runtime/PravegaContainer.java

Add `HOST_IP` environment variable in `PravegaContainer` for client to be able to connect to the segment store
Fix #698 
Add `HOST_IP` environment variable in `PravegaContainer`

[Issue-698] Add `HOST_IP` environment variable

---

README.md
gradle.properties

Upgrade Flink version to `1.16.0` on master branch
Fix #702 
Upgrade `flinkVersion` to `1.16.0` in `gradle.properties`

[Issue-702] Upgrade to Flink 1.16

---

README.md

Signed-off-by: Welkin, Yuan (zywelkin@gmail.com)
Show build status of the repo
Fix [#710](https://github.com/pravega/flink-connectors/issues/710)
Changed
```
[![Build Status](https://img.shields.io/github/workflow/status/pravega/flink-connectors/build)](https://github.com/pravega/flink-connectors/actions/workflows/build.yml?query=branch%3Amaster)
```
to
```
[![Build Status](https://github.com/pravega/flink-connectors/actions/workflows/build.yml/badge.svg)](https://github.com/pravega/flink-connectors/actions/workflows/build.yml?query=branch%3Amaster)
```
Open link (https://github.com/pravega/flink-connectors/actions/workflows/build.yml/badge.svg) in a browser.

[Issue-710] Show build status instead of link

---

src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java

Add some more logs to debug in the `initializeInternalWriter` method in `FlinkPravegaWriter` class 
Fix #714 
Add logs in `FlinkPravegaWriter` class 

[Issue-714] Add more logs for writer initialization

---

src/main/java/io/pravega/connectors/flink/PravegaWriterMode.java
src/main/java/io/pravega/connectors/flink/sink/PravegaCommitter.java
src/main/java/io/pravega/connectors/flink/sink/PravegaEventSink.java
src/main/java/io/pravega/connectors/flink/sink/PravegaEventWriter.java
src/main/java/io/pravega/connectors/flink/sink/PravegaSink.java
src/main/java/io/pravega/connectors/flink/sink/PravegaSinkBuilder.java
src/main/java/io/pravega/connectors/flink/sink/PravegaTransactionalSink.java
src/main/java/io/pravega/connectors/flink/sink/PravegaTransactionalWriter.java
src/test/java/io/pravega/connectors/flink/sink/PravegaSinkBuilderTest.java
src/test/java/io/pravega/connectors/flink/sink/PravegaSinkITCase.java
src/test/java/io/pravega/connectors/flink/sink/PravegaSinkWriterITCase.java

Flink has already provided a enum `DeliveryGuarantee` to describe the delivery guarantee. We will use it instead of `PravegaWriterMode` in our new sink API introduced in #460 
Fix #709 
Replace `PravegaWriterMode` with `DeliveryGuarantee` in new sink API.

[Issue-709] Leverage `DeliveryGuarantee` in new sink API

---

gradle.properties
src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java
src/test/java/io/pravega/connectors/flink/ReaderCheckpointHookTest.java

Add a `cancelOutstandingCheckpoints` call when the checkpoint hits `MaxNumberOfCheckpointsExceededException`
Fixes #719
Add a `cancelOutstandingCheckpoints` call when the checkpoint hits `MaxNumberOfCheckpointsExceededException`

[issue-719] Explicitly cancel outstanding checkpoints when checkpoints get stuck

---

README.md
gradle.properties

Update connector and Pravega version to `0.14.0-SNAPSHOT`, schema registry to `0.7.0-SNAPSHOT`
Fix #724
Update compatibility matrix in `README.md`

[issue-724] Update connector version to 0.14.0-SNAPSHOT

---

gradle.properties
src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java
src/test/java/io/pravega/connectors/flink/ReaderCheckpointHookTest.java

Use `ReaderGroup::initiateCheckpoint(checkpointName)` to perform the checkpoint
Fixes #717 
Update the method
Update the Pravega version

[issue-717] Let Pravega internal thread pool deal with checkpoint

---

README.md
gradle.properties

Update connector to `0.13.1-SNAPSHOT` on `r0.13` branch
Fix #725  
Update `connectorVersion` in `gradle.properties`
Update compatibility matrix in `README.md`

[issue-725] Update connector version to 0.13.1-SNAPSHOT

---

README.md
gradle.properties
gradle/jacoco.gradle
src/test/java/io/pravega/connectors/flink/sink/PravegaSinkWriterITCase.java

Upgrade Flink version to `1.17.1` on master branch
Fix #721
Upgrade `flinkVersion` to `1.17.1` in `gradle.properties`
Address the `Sink` API change [FLINK-30755](https://issues.apache.org/jira/browse/FLINK-30755)
Address the jacoco issue https://github.com/hazelcast/hazelcast/issues/20945

[issue-721] Upgrade Flink 1.17

---

build.gradle
src/main/java/io/pravega/connectors/flink/formats/registry/PravegaRegistryRowDataDeserializationSchema.java
src/main/java/io/pravega/connectors/flink/formats/registry/PravegaRegistryRowDataSerializationSchema.java
src/main/java/io/pravega/connectors/flink/util/MessageToRowConverter.java
src/main/java/io/pravega/connectors/flink/util/RowToMessageConverter.java

Add Protobuf Support
Enable convertion bewtween Flink RowData and Pravega byte array in Protobuf format

Add Protobuf Support

---

README.md
gradle.properties
src/test/java/io/pravega/connectors/flink/PravegaCatalogITCase.java
src/test/java/io/pravega/connectors/flink/sink/PravegaSinkWriterITCase.java

1. Upgrade of Flink version to 1.18.1 on master branch
2. Changes w.r.t [FLINK_32376](https://github.com/apache/flink/pull/22840/commits/b14aae6c197d3b34021286b1d882af14930d4cb5) for Sink Init Context
3. Changes w.r.t [FLINK-31972](https://github.com/apache/flink/pull/22503/files) for fixing the ambiguous usage of `assertThat`
Fix: #730 
Upgrade flinkVersion to 1.18.1 in gradle.properties

[issue-730] Upgrade to flink 1.18.1
