pravega/flink-connectors

- .travis.yml
- build.gradle
- checkstyle/checkstyle.xml
- checkstyle/import-control.xml
- src/main/java/io/pravega/connectors/flink/CheckpointSerializer.java
- src/main/java/io/pravega/connectors/flink/FlinkExactlyOncePravegaWriter.java
- src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
- src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
- src/main/java/io/pravega/connectors/flink/PravegaEventRouter.java
- src/main/java/io/pravega/connectors/flink/PravegaWriterMode.java
- src/main/java/io/pravega/connectors/flink/ReaderCheckpointHook.java
- src/test/java/io/pravega/connectors/flink/FlinkExactlyOncePravegaWriterTest.java
- src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderSavepointTest.java
- src/test/java/io/pravega/connectors/flink/FlinkPravegaReaderTest.java
- src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java
- src/test/java/io/pravega/connectors/flink/ThrottledIntegerGeneratingSource.java
- src/test/java/io/pravega/connectors/flink/utils/FailingMapper.java
- src/test/java/io/pravega/connectors/flink/utils/FlinkMiniClusterWithSavepointCommand.java
- src/test/java/io/pravega/connectors/flink/utils/IntSequenceExactlyOnceValidator.java
- src/test/java/io/pravega/connectors/flink/utils/IntegerGeneratingSource.java
- src/test/java/io/pravega/connectors/flink/utils/IntegerSerializer.java
- src/test/java/io/pravega/connectors/flink/utils/IntentionalException.java
- src/test/java/io/pravega/connectors/flink/utils/NotifyingMapper.java
- src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java
- src/test/java/io/pravega/connectors/flink/utils/SuccessException.java
- src/test/java/io/pravega/connectors/flink/utils/TestUtils.java
- src/test/java/io/pravega/connectors/flink/utils/ThrottledIntegerWriter.java
Fixed license headers to comply with the checkstyle rules
Fixes #22 
Fixes license headers
./gradlew build
> Issue 22: Fix compilation issue

- src/main/java/io/pravega/connectors/flink/serialization/PravegaDeserializationSchema.java
- src/main/java/io/pravega/connectors/flink/serialization/PravegaSerialization.java
- src/main/java/io/pravega/connectors/flink/serialization/PravegaSerializationSchema.java
- src/main/java/io/pravega/connectors/flink/util/FlinkPravegaParams.java
- src/main/java/io/pravega/connectors/flink/util/StreamId.java
- src/test/java/io/pravega/connectors/flink/util/StreamIdTest.java
> Fixed checkstyle errors

- build.gradle
- src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
- src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java
Moved mavenLocal to the top of the repo list and removed references to AckFuture to compile against latest pravega
Moved mavenLocal to the top of the repos
Changed AckFuture references to CompletableFuture and changed `addListener` to `thenRunAsync`
Fix the build to work with the latest pravega
> Updated to work with latest pravega

- gradle.properties
- gradle/java.gradle
- gradle/maven.gradle
Adds publishing of the source and javadoc jars which is required to publish to maven central.
> Added publishing of source/javadoc jars as required by maven central

- .gitattributes
- gradle.properties
- src/main/java/io/pravega/connectors/flink/FlinkExactlyOncePravegaWriter.java
- src/test/java/io/pravega/connectors/flink/FlinkExactlyOncePravegaWriterTest.java
- src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java
- move to Pravega 0.2.0-SNAPSHOT (741f7bb41f06e944e88022d5be58ebacb0d29bb5)
- update to use new txn APIs
- update .gitattributes file for gradle.properties
Compatibility with 0.2+
Closes #60 
Execute `FlinkExactlyOncePravegaWriterTest`
> [issue-60] Pravega txn API changes

- src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
- Fixed accounting of pending writes in FlinkPravegaWriter.
Prevent a stall in the sink following a write error.  Closes #70.   
The code ensures that the count is decremented upon completion, after recording the error (if any).  The order is significant because we notify the flush thread after decrementing.
- use the IT test: `FlinkPravegaWriterTest`.
- note that #67 will provide additional verification tests.
> [issue-70] Fix accounting of pending writes in FlinkPravegaWriter

- src/main/java/io/pravega/connectors/flink/FlinkPravegaReader.java
- disable automatic checkpointing
Closes #83 
Changes the reader group configuration.
`FlinkPravegaReaderTest`
> [issue-83] disable automatic checkpointing

- checkstyle/checkstyle.xml
- gradle.properties
- src/main/java/io/pravega/connectors/flink/FlinkPravegaInputFormat.java
- src/main/java/io/pravega/connectors/flink/PravegaInputSplit.java
- src/test/java/io/pravega/connectors/flink/FlinkPravegaInputFormatITCase.java
- Update to Pravega-0.2 (rc0)
- Incorporate changes to Pravega client related to segment truncation.
- Fix checkstyle failures.
Ensure compatibility with Pravega 0.2.  Closes #92.
Ran integration tests and confirmed
> [Issue 92] Fixed SegmentInfo API call change and checkstyle errors

- gradle.properties
- Update `master` branch to 0.3.0 SNAPSHOT
- To sync with Pravega snapshot version from `master` branch
> [Issue 96] bumped Pravega and Connector version to 0.3.0-SNAPSHOT

- .gitmodules
- settings.gradle
- composite build incorporating Pravega (master)
Satisfy flink-connector build dependency on Pravega as a source dependency.   Closes #88.
- add Pravega (master) as a submodule
- include Pravega project as an 'included' build
> [issue-88] Pravega submodule & composite build

- gradle.properties
- src/main/java/io/pravega/connectors/flink/FlinkPravegaInputFormat.java
Signed-off-by: Flavio Junqueira (fpj) <flavio.junqueira@emc.com>
Fixes #100 , subtask.
Changes a call to the Pravega batch client to reflect API change. Note that this is a change for `r0.2`.
Build.
> [issue-100] Reflect Pravega changes to batch API

- gradle.properties
Prepare for release 0.2.1.
Closes #104
> Issue 104: Prepare release 0.2.1

- .travis.yml
- src/test/resources/logback.xml
Added environment variable to enable console logging in Travis
To log the connector build/test execution results
> [issue-111] added environment variable to enable console logging

- gradle.properties
* updated pravega and connector version to 0.3.0
* updated pravega submodule to v0.3.0-rc0
Fixes #159 
build script changes to fix the pravega and connector version
./gradlew clean build
> [issue-159] Update version info from r0.3 branch (release-prep 0.3.0)

- gradle.properties
Change connectorVersion from 0.3.0 to 0.3.1-SNAPSHOT
To address https://github.com/pravega/flink-connectors/issues/165
updates connector version
> [issue-165] Change connectorVersion to 0.3.1-SNAPSHOT in r0.3 branch

- gradle.properties
* updated pravega and connector version to 0.3.1
* updated pravega submodule to 0.3.1 release commit id
To address the issue https://github.com/pravega/flink-connectors/issues/173
build file changes
run `./gradlew clean build` and make sure the build succeeds
> [issue-173] Change version in r0.3 branch in preparation for release

- gradle.properties
updated r0.3 connector version to 0.3.2-SNAPSHOT
To address issue https://github.com/pravega/flink-connectors/issues/174
build configuration changes
`./gradlew clean build`
> [issue-174] Update Connector version in branch r0.3

- gradle.properties
Updated Pravega version to latest master commit in both gradle properties and submodule.
To address https://github.com/pravega/flink-connectors/issues/184
build script changes
run `./gradlew clean build` and make sure the tests pass
> [issue-184] Update Pravega version to latest master

- gradle.properties
Updated connector version to 0.3.3-SNAPSHOT
To address https://github.com/pravega/flink-connectors/issues/190
build configuration change
> [issue-190] Update connector version to 0.3.3-SNAPSHOT

- gradle.properties
- updated Pravega artifacts to `0.4.0-RC2`
- updated Pravega sub module commit id
To address https://github.com/pravega/flink-connectors/issues/203
updates build configuration to support `0.4.0-rc2` version of Pravega
`./gradlew clean build` should succeed
> [Issue-203] Update Pravega version to 0.4.0-RC2

- gradle.properties
Signed-off-by: Elizabeth Bain <elizabeth.bain@emc.com>
* updated Pravega version to v0.4.0-rc5
* updated Pravega submodule commit to d99411b1cb805f9d6c7374db566801e7eb724851
To address the issue https://github.com/pravega/flink-connectors/issues/206
build configuration changes
> [Issue-206] Upgrade Pravega version to 0.4.0 RC5

- gradle.properties
* updated Pravega version to 0.4.0
* updated connector version to 0.4.0
To address the issue https://github.com/pravega/flink-connectors/issues/208
build configuration changes
> [issue-208] Prepare connector for 0.4.0 release

- gradle.properties
advanced the connector version to 0.4.1-SNAPSHOT to support future release
To address https://github.com/pravega/flink-connectors/issues/210
updates connector version in gradle configuration
build should pass
> [issue-210] Update connector version from release r0.4 branch

- .travis.yml
- build.gradle
- gradle.properties
- gradle/jacoco.gradle
* Enables codecov for this repository
Fixes #220
No code change, configuration to enable codecov.
Should see a codecov report.
> [issue-220] Enable code coverage in .travis.yml

- gradle.properties
Updated Pravega artifact version to `r0.5` artifact
To address https://github.com/pravega/flink-connectors/issues/229
build configuration change
> [issue-229] Update connector to use Pravega r0.5 artifacts

- documentation/src/docs/batch.md
- documentation/src/docs/configurations.md
- documentation/src/docs/streaming.md
Signed-off-by: Aparna <Aparna.Rr@emc.com>
1. Version number should be changed from 0.4.0 to 0.5.0
documentation/streaming.md (Section streamcuts)
2. Format fix:
documentation/batch.md (section: input streams, stream cuts)
Issue #222
> [Issue 222:] Version changed from v0.4.2 to v0.5.0 in documents

- gradle.properties
* updated version to 0.6.0-SNAPSHOT
To address https://github.com/pravega/flink-connectors/issues/235
bumped the snapshot version to next major
> [issue-235] Update connector version in master

- gradle.properties
- Updated Pravega and Connector version to 0.5.0
- Updated Pravega sub-module commit to r0.5 
Fixes https://github.com/pravega/flink-connectors/issues/254
`gradle.properties` and Pravega sub-module configuration changes
> [Issue-254] Prepare for 0.5 release

- gradle.properties
- Update connector version to 0.5.1-SNAPSHOT
Fixes https://github.com/pravega/flink-connectors/issues/257
> [issue-257] Update connector version to 0.5.1-SNAPSHOT

- documentation/src/docs/getting-started.md
- documentation/src/docs/quickstart.md
- documentation/src/docs/streaming.md
- documentation/src/docs/table-api.md
Update the documentation
Update the documentation with multi-Flink-version and watermarking support
`./gradlew clean mkdocsBuild` passes.
> [issue-284] Update document for 0.6 release

- gradle.properties
**Please merge it after Pravega 0.6 release and #289**
- [issue-286] Prepare for 0.6 release
Fix #286 
`gradle.properties` and Pravega sub-module configuration changes
> [issue-286] Prepare for 0.6 release

- gradle.properties
- Update connector version to `0.7.0-SNAPSHOT`
- Update the Pravega version and submodule to `0.7.0-50.719995b-SNAPSHOT`
Fixes #292 
> [issue-292] Update connector and submodule versions

- gradle.properties
* Update connector version to `0.6.2-SNAPSHOT`
* Update signing.keyId to None
Fixes #307
gradle.properties changes
> [issue-307] Update connector version to 0.6.2-SNAPSHOT

- src/test/java/io/pravega/connectors/flink/serialization/PravegaSerializationTest.java
Signed-off-by: Guangfeng Xu <Guangfeng.Xu@dell.com>
Add test case for `JsonSerializer`
Fixes #333 
Check the correctness of the `io.pravega.connectors.flink.serialization.JsonSerializer`
> [issue 333] Add test case for JsonSerializer

- gradle.properties
- Updated Pravega and Connector version to `0.7.0`
- Updated Pravega sub-module commit to `r0.7`
Fixes #339 
`gradle.properties` and Pravega sub-module configuration changes
> [issue-339] Prepare for 0.7 release

- gradle.properties
Update connector version to 0.8.0-SNAPSHOT
Fix #352 
pravega submodule update
`./gradlew clean build `should pass
> [issue-352] Update Connector version to 0.8.0-SNAPSHOT

- gradle.properties
Update connector version to 0.7.1-SNAPSHOT in branch r-0.7
Fix #353 
> [Issue-353] Update connector version in branch r0.7

- documentation/src/docs/quickstart.md
Running / Deploying the Application part in `quickstart.md`
Fixes #372
Add jar packaging rules in the documentation.
Only documentation Change.
> [issue-372] Mention package rules in doc.

- src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java
Signed-off-by: Brian Zhou <b.zhou@dell.com>
Call Close for Pravega ClientFactory in unit tests
Fixes #407 
Record the `eventStreamClientFactory` reference to avoid extra initialization. Call close when the Pravega standalone cluster for test is destroyed.
Target to master, should cherry-pick to all `0.8` branch
> [issue-407] Call Close for Pravega ClientFactory in unit tests

- gradle.properties
- Upgrade to Flink 1.10.3
Fixes #443 
Upgrade to Flink 1.10.3
> [issue-443] Upgrade to Flink 1.10.3

- gradle.properties
- src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterITCase.java
- src/test/java/io/pravega/connectors/flink/dynamic/table/FlinkPravegaDynamicTableITCase.java
- Update Pravega client to latest 0.9
Fixes #450 
- Update Pravega client to `0.9.0-2765.79a6eb7-SNAPSHOT`
- Update Pravega submodule to commit `79a6eb7`
> [Issue-450] Update pravega client to 0.9.0-2765

- gradle.properties
Update connector version to 0.10.0-SNAPSHOT
Fix #462 
pravega submodule update
> [issue-462] Update connector to 0.10.0-SNAPSHOT

- .gitmodules
- documentation/src/docs/getting-started.md
- gradle.properties
- settings.gradle
Remove Pravega submodule
Fixes #461
* Remove the use of `usePravegaVersionSubModule` in both `gradle.properties` and `settings.gradle`.
* `.gitmodules` was also removed.
* Update the doc `documentation\src\docs\getting-started.md` where submodule is mentioned.
`gradlew clean build` passes
> [Issue-461] Remove Pravega submodule

- gradle.properties
Update connector version to 0.9.1-SNAPSHOT in branch r0.9
Fix #466 
gradle.properties changes
pass `./gradlew clean build`
> [Issue-466] Update connector version in branch r0.9

- README.md
Add compatibility matrix in readme doc
Fix #467 
Add compatibility matrix in README.md
> [issue-467] Improve the readme doc with compatibility matrix

- gradle.properties
Upgrade pravega version to the latest commit [pravega/pravega@1d3cd4b](https://github.com/pravega/pravega/commit/1d3cd4b)
Fix #485 
Upgrade pravega version to the latest commit [pravega/pravega@1d3cd4b](https://github.com/pravega/pravega/commit/1d3cd4b)
`gradlew build` passes
> [Issue-485] Upgrade Pravega 0.9 to the latest snapshot version

- gradle.properties
Upgrade pravega version to the latest commit [pravega/pravega@0e600c1](https://github.com/pravega/pravega/commit/0e600c1)
Fix #484 
Upgrade pravega version to the latest commit [pravega/pravega@0e600c1](https://github.com/pravega/pravega/commit/0e600c1)
`gradlew build` passes
> [Issue-484] Upgrade Pravega 0.10 to the latest snapshot version

- src/main/java/io/pravega/connectors/flink/dynamic/table/FlinkPravegaDynamicTableFactory.java
- src/main/java/io/pravega/connectors/flink/dynamic/table/PravegaOptions.java
- src/main/java/io/pravega/connectors/flink/formats/registry/PravegaRegistryFormatFactory.java
- src/main/java/io/pravega/connectors/flink/formats/registry/PravegaRegistryOptions.java
- src/main/java/io/pravega/connectors/flink/table/catalog/pravega/PravegaCatalog.java
- src/main/java/io/pravega/connectors/flink/table/catalog/pravega/descriptors/PravegaCatalogDescriptor.java
- src/main/java/io/pravega/connectors/flink/table/catalog/pravega/descriptors/PravegaCatalogValidator.java
Enhance some names and descriptions of options for Pravega catalog. 
Fix #531 
Change naming and descriptions in `PravegaRegistryOptions` and `PravegaOptions`.
> [issue-531] Enhance naming in Pravega catalog options

- README.md
The current README is pinned with an outdating CI build badge. And also we need more badges😁
Fixes #579 
No code changes.
These new badges look good and awesome😎
> [Issue-579] More badges😁

- documentation/src/docs/batch.md
- documentation/src/docs/catalog.md
- documentation/src/docs/configurations.md
- documentation/src/docs/dev-guide.md
- documentation/src/docs/getting-started.md
- documentation/src/docs/index.md
- documentation/src/docs/metrics.md
- documentation/src/docs/quickstart.md
- documentation/src/docs/serialization.md
- documentation/src/docs/streaming.md
- documentation/src/docs/table-api.md
- documentation/src/mkdocs.yml
Update doc to have the right table of content.
Fixes #584 
Indent list in doc with 4 spaces.
`.\gradlew clean mkdocsBuild` have the right tabe.
> [Issue-584] Update doc to have the right table of content

- gradle.properties
Signed-off-by: Fan Yang <fan.yang5@emc.com>
- Upgrade Pravega client version to the latest commit https://github.com/pravega/pravega/commit/ea3db6f1ce90cfb436d3af3589ec96e44ff1312f
- Upgrade schema-registry version to the latest commit https://github.com/pravega/schema-registry/commit/dee41542b711da47bc540be2aa4bae0c8cc2ec3e
Fix #586 
Change pravega and schema-registry version in `gradle.properties`
> [issue-586] Upgrade Pravega client and schema-registry version

- src/main/java/io/pravega/connectors/flink/table/catalog/pravega/PravegaCatalog.java
- src/main/java/io/pravega/connectors/flink/table/catalog/pravega/descriptors/PravegaCatalogDescriptor.java
- src/main/java/io/pravega/connectors/flink/table/catalog/pravega/descriptors/PravegaCatalogValidator.java
- src/main/java/io/pravega/connectors/flink/table/catalog/pravega/factories/PravegaCatalogFactory.java
- src/test/java/io/pravega/connectors/flink/PravegaCatalogITCase.java
- src/test/java/io/pravega/connectors/flink/formats/registry/PravegaRegistrySeDeITCase.java
- src/test/java/io/pravega/connectors/flink/utils/IntegerGeneratingSource.java
- src/test/java/io/pravega/connectors/flink/utils/SetupUtils.java
- Merge fixes in #578 into branch r0.10-flink1.12
- Fix HEADER in some classes which will be deleted in flink-1.13
Fix #589 
Add Pravega security options in Catalog factory options so that we can create StreamManager upon ClientConfig that contains security configs.
Set enableTls to true for integration tests.
> [issue-589] Cherrypick #578 into r0.10-flink1.12

- gradle.properties
Update connector version to 0.11.0-SNAPSHOT
Fix #605 
> [issue-605] Update connector version to 0.11.0-SNAPSHOT

- gradle.properties
Update connector version to 0.10.2-SNAPSHOT in branch `r0.10`
Fix #606 
> [issue-606] Update connector version in branch `r0.10`

- src/main/resources/META-INF/services/org.apache.flink.table.factories.TableFactory
Fix table factory to fix test failure in branch `r0.11-flink1.12`.
Fix #626 
Remove deprecated class in TableFactory and add missing class
> [Issue 626] Fix test failure in branch `r0.11-flink1.12`

- documentation/src/docs/catalog.md
Refine the catalog document to improve readability
Fix #639 
- Change the format factory part to add some explanation
- Add a list a table of all the catalog options
> [issue-639] Refine catalog document

- README.md
Update links in *Compatibility Matrix* `r0.10` so they correspond to the actual branch.
Fixes #642 
No code changes.
*Compatibility Matrix* in `README.md` should be correct.
> [Issue-642] Fix links in readme

- NOTICE
- Update `NOTICE` file to reflect the current year 2022
Fix #645 
- Update year range in `NOTICE` file
> [issue-645] Update the year 2022 in copyright

- NOTICE
- build.gradle
- documentation/src/docs/catalog.md
- documentation/src/docs/table-api.md
- gradle.properties
- src/main/java/io/pravega/connectors/flink/FlinkPravegaOutputFormat.java
- src/main/java/io/pravega/connectors/flink/FlinkPravegaWriter.java
- src/main/java/io/pravega/connectors/flink/serialization/SerializerFromSchemaRegistry.java
- src/main/java/io/pravega/connectors/flink/source/PravegaSource.java
- src/main/java/io/pravega/connectors/flink/source/PravegaSourceBuilder.java
- src/main/java/io/pravega/connectors/flink/source/PravegaSourceOptions.java
- src/main/java/io/pravega/connectors/flink/source/enumerator/PravegaSplitEnumerator.java
- src/main/java/io/pravega/connectors/flink/source/reader/PravegaFetcherManager.java
- src/main/java/io/pravega/connectors/flink/source/reader/PravegaRecordEmitter.java
- src/main/java/io/pravega/connectors/flink/source/reader/PravegaSourceReader.java
- src/main/java/io/pravega/connectors/flink/source/reader/PravegaSplitReader.java
- src/main/java/io/pravega/connectors/flink/source/split/PravegaSplit.java
- src/main/java/io/pravega/connectors/flink/source/split/PravegaSplitSerializer.java
- src/main/java/io/pravega/connectors/flink/util/SchemaRegistryUtils.java
- src/test/java/io/pravega/connectors/flink/FlinkPravegaOutputFormatTest.java
- src/test/java/io/pravega/connectors/flink/FlinkPravegaSchemaRegistryWriterTestITCase.java
- src/test/java/io/pravega/connectors/flink/FlinkPravegaWriterTest.java
- src/test/java/io/pravega/connectors/flink/ReaderCheckpointHookTest.java
- src/test/java/io/pravega/connectors/flink/dynamic/table/FlinkPravegaDynamicTableITCase.java
- src/test/java/io/pravega/connectors/flink/sink/PravegaTransactionWriterTest.java
- src/test/java/io/pravega/connectors/flink/source/FlinkPravegaSourceITCase.java
- src/test/java/io/pravega/connectors/flink/source/enumerator/FlinkPravegaSplitEnumeratorTest.java
- src/test/java/io/pravega/connectors/flink/source/reader/FlinkPravegaSourceReaderTest.java
- src/test/java/io/pravega/connectors/flink/source/reader/FlinkPravegaSplitReaderTest.java
Merge the latest master to be compatible with flink 1.15
Fix #666 
Upgrade connector to be compatible with these changes.
* [FLINK-24427](https://issues.apache.org/jira/browse/FLINK-24427) Hide Scala in flink-table-planner from API
* [FLINK-24857](https://issues.apache.org/jira/browse/FLINK-24857) Upgrade SourceReaderTestBase to Use Junit 5
> [Issue-666] Update flink-1.15-test branch
